version: '3'
services:
  register-center:
    image: df2docker/register-center
    restart: always
    container_name: register-center
    hostname: register-center
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 50M
    networks:
      - app
    ports:
      - "8761:8761"
  config-server:
    image: df2docker/config-server
    restart: always
    container_name: config-server
    hostname: config-server
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 50M
    ports:
      - "9090:9090"
    networks:
      - app
    depends_on:
      - register-center
  auth-center:
    image: df2docker/auth-center
    restart: always
    container_name: auth-center
    hostname: auth-center
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 50M
    networks:
      - app
    depends_on:
      - register-center
      - config-server
  backend-server:
    image: df2docker/backend-server
    restart: always
    container_name: backend-server
    hostname: backend-server
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 50M
    networks:
      - app
    depends_on:
      - register-center
      - config-server
  zuul-server:
    image: df2docker/zuul-server
    restart: always
    container_name: zuul-server
    hostname: zuul-server
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 50M
    ports:
      - "9001:9001"
    networks:
      - app
    depends_on:
      - register-center
      - config-server
networks:
  app:
    external: true
